from __future__ import annotations

EXAMPLE_TEXTS = {
    "en": {
        "Albert Einstein": "Albert Einstein was a German-born theoretical physicist who is widely held to be one of the greatest and most influential scientists of all time. Best known for developing the theory of relativity, Einstein also made important contributions to quantum mechanics. His mass–energy equivalence formula E = mc², which arises from relativity theory, has been called 'the world's most famous equation'. He received the 1921 Nobel Prize in Physics for his services to theoretical physics, and especially for his discovery of the law of the photoelectric effect.",
        "AAAI": "The Association for the Advancement of Artificial Intelligence (AAAI) is an international scientific society devoted to promote research in, and responsible use of, artificial intelligence (AI). AAAI also aims to increase public understanding of AI, improve the teaching and training of AI practitioners, and provide guidance for research planners and funders concerning the importance and potential of current AI developments and future directions.",
        "Singapore": "Singapore, officially the Republic of Singapore, is a sovereign country as well as a city-state. It is nicknamed as 'The Lion City', 'The Garden City' or 'The Little Red Dot'. It is an island state at the southern end of the Malay Peninsula in Southeast Asia, between the Straits of Malacca and the South China Sea. Singapore is about one degree of latitude (137 kilometres or 85 miles) north of the equator. About 5.70 million people live in Singapore. About 3.31 million are citizens. Most of them are ethnically Chinese, Malay, or Indian, as well as a smaller number of other Asians and Europeans.",
        "AAAI-2026": "In 2026, the AAAI Conference on Artificial Intelligence was held in Singapore, bringing together researchers and practitioners from academia, industry, and government. The conference featured peer-reviewed technical papers, invited talks, workshops, tutorials, and poster sessions covering a broad range of topics in artificial intelligence. Singapore served as the host location for the event, providing conference facilities and infrastructure to support international participation. The 2026 edition continued AAAI’s annual conference series and contributed to the dissemination of current research results and ongoing developments in the field of artificial intelligence.",
        "TP53": "p53, also known as tumor protein p53 (TP53), is a regulatory transcription factor protein that is often mutated in human cancers. p53 has been described as 'the guardian of the genome' because of its role in conserving stability by preventing genome mutation. Hence TP53 is classified as a tumor suppressor gene. The TP53 gene is the most frequently mutated gene (>50%) in human cancer, indicating that the TP53 gene plays a crucial role in preventing cancer formation. TP53 gene encodes proteins that bind to DNA and regulate gene expression to prevent mutations of the genome.",
        "p21": "p21Cip1 (alternatively p21Waf1), also known as cyclin-dependent kinase inhibitor 1 or CDK-interacting protein 1, is a cyclin-dependent kinase inhibitor (CKI) that is capable of inhibiting all cyclin/CDK complexes. p21 represents a major target of p53 activity and thus is associated with linking DNA damage to cell cycle arrest. This protein is encoded by the CDKN1A gene located on chromosome 6 (6p21.2) in humans.",
    },
    "ru": {
        "Профиль предпринимателя Баранова Егора": ("Баранов Егор Владимирович, 28.04.1970, генеральный директор/Владелец: ООО \"СК БУМ\"\nАдреса: г. Москва, ул. Речная, д. 5, г. Москва, ул. Островная, д. 78\nE-mail: bumsk@mail.ru, bumsk@yandex.ru\n\nКоммерческая и трудовая деятельность: Окончил Московский авиационный институт (МАИ) в 1998 году. 03.2001 - 12.2010, Генеральный директор ООО \"БУМ 2000\"; 11.2009 - 01.2016 Генеральный директор/Владелец ООО \"ЭКОЛАЙТ\"; 02.2009 - 03.2013 Генеральный директор/Владелец ООО \"БУМЛАЙТ\", 12.2012 - 02.2018 ООО \"БУМАГА\"; 09.2018 - н.в. Генеральный директор/Владелец ООО \"СК БУМ\"; 05.2024 - н.в. учеридитель ОГРНИП Баранов Е.В.(Сбор неопасных отходов).\n"),
        "Профиль предпринимателя Орехина Владимира": ("Орехин Владимир Васильевич\nГенеральный директор ОСГ МОСКВА, Управляющий директор ОСГ МОСКВА, АСТАНА, МИНСК, ЕРЕВАН\nРодился: 11.09.1974 г., в гор. Кизел, Пермского края\nАдреса: Московская обл., г. Красногорск, ул. Озерная, д. 56, +750577650233\nE-mail: v.orehin@mail.ru, v.orehin@mcmgmt.ru\nОбразование: Московский авиационный институт (МАИ) - 1998, имеет диплом MBA London Metropolitan Institute в области управления. \nКарьера из открытых источников: В 1998 г. начал работу в компании Nokia с позиции менеджера поддержки продаж.  В 1999–2002 гг. в штаб-квартире Nokia в Хельсинки занимался развитием бизнеса в Северной Америке. Впоследствии в компании SouthLine отвечал за развитие бизнеса беспроводной связи в России и СНГ. Занимал руководящие должности в сфере телекоммуникаций и IT-компаний, в том числе North Networks, Siemens, Ericsson. В 2013 году пришел в компанию Division Buisness solutions и проработал там 2,5 года в качестве генерального директора. В январе 2017 года IBM объявила о назначении Орехина Владимира на должность руководителя области в России и странах СНГ. С 2018 года Орехин работает на должности управляющего директора Reg.ru Cloud. Отвечает за направление прямых линий V2V- и партнерских продаж, а также за развитие подмосковного региона Reg.ru Cloud. В мае 2020 года на протяжении всего процесса интеграции бизнес-процессов и институционального потенциала компании генеральным директором OSG Music Management в России был назначен Орехин Владимир. На ноябрь 2020 года он также является управляющим директором OSG МОСКВА, КИЕВ, АСТАНА, МИНСК, ЕРЕВАН. \n05.2020 - н.в. ООО \"ОСГ МЬЮЗИК МЕНЕДЖМЕНТ\", Генеральный директор\n05.2020 - н.в. ООО \"ОСГ МЬЮЗИК МЕНЕДЖМЕНТ ЦЕНТР\", Генеральный директор\n05.2020 - н.в. ООО \"ОСГ МЬЮЗИК МЕНЕДЖМЕНТ КРИПТО\", Генеральный директор\n"),
        "Профиль компании Южная Газовая Станция": ("ЮЛ Южная Газовая Станция. Зарегистрирована 26.08.2002 г. по адресу Приморский край, г. Находка, ул. Находский проспект, д. 96.\n\nОсновной вид деятельности (отрасль): транспорт грузов \nРуководитель: Локтев Юрий Сергеевич (генеральный директор)\n\nБенефициар: Ветров Евгений Викторович. \nУставный капитал: 14 700 000 ₽ (8.09.2005)\nСреднесписочная численность: 75 чел. (на 31.12.2025)\nФинансовые показатели на 2024 год:\nДоходы: 2 983 790 000 ₽\nРасходы: 1 380 567 000 ₽\nВыручка от продажи: 2 390 162 000 ₽\nЧистая прибыль: 1 986 195 000 ₽\nЧистые активы: 4 717 635 000 ₽\nОсновные средства: 892 665 000 ₽\nДенежный поток: 74 947 000 ₽\nНалоги: 552 662 602 ₽\n«Кредитный лимит»: 1 297 810 000 ₽\nЛицензии и разрешения: 8 лицензий\nЗаблокированные счета: на 20.12.2025 — нет действующих решений\nФакторы внимания: указаны виды деятельности, подлежащие лицензированию; исключен из реестра МСП 10.08.2025.\ne-mail: sgt@sgtdv.ru; web: https://sgtdv.ru,\nГенеральным директором и владельцем ООО «Южная Газовая Станция» является  Ветров Евгений Викторович, 05.12.1977, тел. 79865693564, 79157944631 (Ветров Е. В. – сын убитого в 2002 году генерального директора ОАО «Южный порт» Ветрова Виктора).\n\n"),
        "Профиль предпримнимателя Ветрова Евгения": ("Ветров Евгений Викторович - Член Совета директоров Ассоциации, Бывший генеральный директор ООО «Южная Газовая Станция\nРодился: 05.12.1977 в гор. Кизел, Пермского края.\nАдреса: г. Москва, Литовский Бульвар, д. 28\nг. Москва, Дохтуровский, д. 8\nПриморский край, г. Находка, ул. Речная, д. 3\nE-mail: sgt@sgtdv.ru\nСоц. сети: https://vk.com/id87877856325\nОбразование: Московский авиационный институт (МАИ) \nВ 2021 г. занял 54 место в рейтинге ТОП 100 Богатейших людей Приморья. (Сумма активов 2 705 545 600 ₽;  выручка 543 100 000 ₽;  чистая прибыль 98 054 400 ₽).\n\n, \nТрудовая деятельность: \n2000 - «Компания Дитра, Фрахтовальщик;\n2000 – 2002 ОАО «Сельфлот», Старший специалист;\n2002 - 2005 ЗАО «Южникель», Зам. начальника портово-фрахтового отдела;\n2003 – ОАО «Банк ВнешТор»\n2005 - 2006 ООО «Трансхим» - директор по корпоративной политике и финансам;\n2007 – 2012 ООО «Наливгруз порт» - Генеральный директор;\nС 2012 года ООО “Южная Газовая Станция” - Председатель Совета директоров;\n2015 - ЗАО \"Южникель\", Главный советник. Заместитель начальника отдела портово-фрахтовых операций;\n2015 - ЗАО \"Российский Контейнерный Сервис\", Член совета директоров;\nC 2017 года ООО «Нефтехим компания» - Генеральный директор; \nС 2024 года ООО \"Южная Газовая Станция\" - Генеральный директор.\nКоммерческая деятельность:\n09.2006 - 11.2012 ООО \"НАЛИВГРУЗ Порт\", Генеральный директор, Совладелец;\n11.2012 - н.в. ООО \"Южная Газовая Станция\", Владелец с 02.2020 г., Бывший генеральный директор;\n2016 - АО \"Восточный терминал\", Бывший председатель совета директоров, Бывший совладелец;\n09.2017 - 10.2024 ООО \"ВОСТОЧНЫЙ ЗАВОД КЕРАМИКИ\", Бывший совладелец;\n09.2016 - 02.2018 ООО \"КОМПЛЕКС СПТ\", Бывший совладелец;\n09.2016 - 02.2017 ООО \"ВОСТОКСТРОЙ\", Бывший совладелец;\n08.2018 - 10.2026 ООО \"ТРАНСХИМ\", Бывший генеральный директор, Совладелец,Владелец, \n\nРодственники:\n Сестра, Орехина Елена Викторовна, 31.11.1988, член правления «Южной Газовой Станции»\nАдрес: Москва г, Клементьевский пер, дом № 6\n\nТрудовая деятельность: 2008 - ЗАО «Южникель», Ведущий специалист управления внешних инвестиций;\n2010 - ООО “Восточный эксперт”, Ведущий специалист;\n07.2012 - 10.2014 ООО \"ВОСТОЧНАЯ БАЛОЧНАЯ КОМПАНИЯ\", Владелец\n05.2017 - 04.2024 ООО \"НЕФТЕХИМ компания\", Совладелец;\n2022 - Член правления \"Южной Газовой станции\"\n\nОтец, Ветров Виктор Сергеевич, 23.02.1947 \nС 1998 по 2001 гг. Генеральный директор ОАО «Южный терминал». Убит в 2002 г.\n\nМать, Ветрова Лариса Ивановна, 17.10.1948 \nДо 2006 г. была совладельцем ООО \"ВОСТОК-ТРАНС\n"),
        "Профиль компании СК БУМ": ("ЮЛ - СК БУМ: Зарегистрирована: 28.07.2016 г., по адресу: г. Москва, ул. Молотовская, д. 8, стр. 3, помещ. 10БА, ОГРН 1177757900290\nОсновной вид деятельности: Торговля оптовая бумагой и картоном\nГенеральный директор/Владелец: Баранов Егор Владимирович (ИНН 7720357487662)\nРазмер предприятия: Малые предприятия.\nСредняя численность: 17 чел. на 31.12.2025 г. \nУставной капитал: 35 000 руб. на 08.2016 г.\nДоходы на 2025 г. 545 418 000 руб. \nРасходы на 2025 г. 470 087 000 руб.\nНалоги на 2025 г. 1 695 453 руб.\n«Кредитный лимит» 3 340 000 руб.\nВыручка от продажи на 2025 г. 450 455 000 руб.\nЧистая прибыль на 2025 г. 6 889 000 руб.\nЧистые активы на 2025 г. 32 789 000 руб.\nОсновные средства на 2025 г. 15 189 000 руб.\nДенежный поток на 2024 г. -1 152 000 руб.\nE-mail: bumsk@yandex.ru\nСайт: https://www.bumsk.ru/")
                
    },
}

PERSONAL_SEARCH_PROMPTS = {
    "en": (
        "Find and extract fresh, up-to-date information from the internet about "
        "{person}, and return one paragraph summarizing it. Return only the "
        "paragraph, with no other text."
    ),
    "ru": (
        "Найдите и извлеките из интернета свежую и актуальную информацию о "
        "{person} и верните параграф, который суммирует эту информацию. "
        "Верните только параграф, никакого другого текста."
    ),
}


def get_example_texts(language: str) -> dict[str, str]:
    return EXAMPLE_TEXTS.get(language, EXAMPLE_TEXTS["en"])


def personal_search_prompt(language: str, person: str) -> str:
    template = PERSONAL_SEARCH_PROMPTS.get(language, PERSONAL_SEARCH_PROMPTS["en"])
    return template.format(person=person)
